<html dir="ltr" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta content="ru" http-equiv="Content-Language" />
    <title>Портфолио. Александр Шестаков</title>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <link href="style.css" rel="stylesheet" type="text/css" /> 
    <script type="text/javascript" src="js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
</head>
<body>
    <div id="wrapper">
        <div id="header">
            <div id="slogan">
                * Верстка сайтов<br />
                * Web-программирование<br />
                * Программирование под Windows<br />
                * Базы данных
            </div>
            <div id="portfolio">Портфолио</div>
            <div id="fio">Александр Шестаков</div>
        </div>
        <div id="main-menu">
            <a id="a-index" href="index.php" class="selected">Портфолио</a>
            <a id="a-practice" href="practice.php">Знания и навыки</a>
            <a id="a-contact" href="contact.php">Контакты</a>
            <div class="clear"></div>
        </div>
        <br />
        <div class="line"></div>
        <br />
        <br />