<ul id="menu">
    <li data-div="cp">Мой первый сайт</li>
    <li data-div="it-ho">Компьютерная помощь <br />it-ho.ru</li>
    <li data-div="ls">http://groupls.ru/</li>
    <li data-div="web">Web-приложение</li>
    <li data-div="pp">Windows-приложение</li>
</ul>

<div id="v-line"></div>

<div data-div="cp" class="content">
    <div class="description">
        Мой первый сайт. Выполнен на html и css. <br />
        Админки не было, о существовании CMS я тогда только догадывался.<br />
        Пробовал применять простенькие jquery-анимации и писать php-скрипты.<br /><br />
        [2019 год] Сайт уже не работает
    </div>
    <div class="image">Скриншот</div>
    <img src="images/cp.png" alt="" />
</div>

<div data-div="it-ho" class="content">
    <div class="description">
        Сайт бесплатной компьютерной помощи онлайн.<br />
        Написан на чистом php, фреймворки не использовал. <br />
        Начал использовать MySql на сайте и писать sql-запросы.<br />
        Узнал, что такое ajax и json, и начал активно применять на практике.<br />
        Админка для редактирования статей блога написана с использованием js+jquery+php+mysql.
    </div>
    <a href="http://it-ho.ru/" title="" target="_blank">Ссылка на сайт</a>
    <div class="image">Скриншот</div>
    <img src="images/it-ho.png" alt="" />
</div>

<div data-div="ls" class="content">
    <div class="description">
        Первый сайт, написанный под системой управления Modx Evo.
        Использовал только базовые понятия Modx: шаблоны, чанки, сниппеты
        <br /><br />
        [2019 год] Сайт уже переделан
    </div>
    <div class="image">Скриншот</div>
    <img src="images/ls.png" alt="" />
</div>


<div data-div="web" class="content">
    <div class="description">
        Web-приложение (создавалось только под Google Chrome).<br /> 
        Система управления заказами, задачами, сотрудниками, финансами для мебельного салона.<br />
        Использовались: html, css, javascript, jquery, ajax-запросы, php, mysql. 
        Большинство операций выполняются без перезагрузки страницы. Использовались сторонние jquery-плагины<br /><br />
        [2019 год] Приложение показать уже не могу
    </div>
    <div class="image">Скриншот</div>
    <img src="images/web.png" alt="" />
</div>

<div data-div="pp" class="content">
    <div class="description">
        Моя последняя работа под Windows. <br />
        Это комплекс приложений для создания и проведения психологических исследований сотрудников предприятия.
        Трехзвенная архитектура, одно серверное приложение и три клиентских. Написаны на Delphi 2009 с СУБД MySql.
        При написании приложения часть логики серверной части была перенесена на сервер MySql (хранимые процедуры, функции и триггеры)<br />
        Работает как на локальном компьютере, так и через локальную сеть и интернет
        <br /><br />
        [2019 год] К сожалению, не могу показать даже скриншот. Программа до сих пор работает, но все права принадлежат заказчику :-)
    </div>
</div>
